**Subject Name :** **Introduction to Data Science Lab.** <br>
**Subject Code :** **MCAD191A** <br>
**Topic :** **NumPy** <br>
**Department of Computer Applications** <br>
**Seacom Skills University**

<p>NumPy (Numerical Python) is a powerful open-source library essential for numerical computing in Python.<br>
It offers an efficient array object (ndarray), tools for array manipulation, mathematical, logical, statistical, and linear algebra operations, and underpins much of the Python scientific stack.</p>

**Installation**

In [1]:
pip install numpy

**Importing NumPy**

In [2]:
import numpy as np

**Creating NumPy Arrays**

In [3]:
#from a Python list
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


**Multi-Dimensional Array**

**0D Arrays**

In [4]:
import numpy as np
arr0 = np.array(2025)
print(arr0)

2025


**1D Arrays**

In [5]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

[10 20 30 40 50]


**2D Arrays**

In [6]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


**3D Arrays**

In [7]:
arr3 = np.array([[["India", "United States", "Ireland"], ["Japan", "Finland", "Australia"]], [["Argentina", "Brazil", "Spain"], ["Canada", "Germany", "Nepal"]]])
print(arr3)

[[['India' 'United States' 'Ireland']
  ['Japan' 'Finland' 'Australia']]

 [['Argentina' 'Brazil' 'Spain']
  ['Canada' 'Germany' 'Nepal']]]


**Number of Dimensions**

In [8]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


**Array of Zeros**

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**Array of Ones**

In [10]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Array with a Range**

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

**Linearly spaced Array**

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**Array Attributes**

In [13]:
arr = np.array([[50, 60, 30], [45, 57, 78]])

print(arr.shape)
print(arr.ndim)    # number of dimensions
print(arr.size)    # total elements
print(arr.dtype)   # data type

(2, 3)
2
6
int64


**Basic Array Operations**

**Element-wise operations**

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a / b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


**Mathematical operations**

In [15]:
np.sqrt(a)
np.sum(a)
np.mean(a)
np.max(a)
np.min(a)

print(np.sqrt(a))
print(np.sum(a))
print(np.mean(a))
print(np.max(a))

[1.         1.41421356 1.73205081]
6
2.0
3


**Array Indexing**

**0D Array**

In [16]:
arr = np.array(500)
print(arr)

#Since it has only one element, indexing is trivial.

500


**1D Array**

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


**2D Array**

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr[0, 0])
print(arr[0, 2])
print(arr[1, 1])

1
3
5


**3D Array**

In [19]:
arr = np.array([ [[1, 2, 3],
                  [4, 5, 6]],

                 [[7, 8, 9],
                  [10, 11, 12]] ])

print(arr[0, 0, 0])
print(arr[1, 1, 2])
print(arr[0, 1, 1])

1
12
5


**Negative Indexing**

**1D Array**

In [20]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])
print(arr[-2])
print(arr[-5])

50
40
10


**2D Array**

In [21]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr[-1, -1])
print(arr[-1, -2])
print(arr[-2, -3])

60
50
10


**3D Array**

In [22]:
arr = np.array([ [[1, 2, 3],
                  [4, 5, 6]],

                 [[7, 8, 9],
                  [10, 11, 12]] ])

print(arr[-1, -1, -1])
print(arr[-2, -2, -2])

12
2


**Array Slicing**

**0D Array**<br>
A 0D array has only one element, so slicing is not possible.

**1D Array**

**Basic slice**

In [23]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


**Slice from start**

In [24]:
print(arr[:3])

[10 20 30]


**Slice till end**

In [25]:
print(arr[2:])

[30 40 50]


**Using step**

In [26]:
print(arr[0:5:2])

[10 30 50]


**2D Array**

**Slice a row**

In [27]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr[0, :])

[1 2 3 4]


**Slice a column**

In [28]:
print(arr[:, 1])

[2 6]


**Sub-matrix slice**

In [29]:
print(arr[0:2, 1:3])

[[2 3]
 [6 7]]


**Every 2nd column**

In [30]:
print(arr[:, ::2])

[[1 3]
 [5 7]]


**3D Array**

In [31]:
arr = np.array([ [[1, 2, 3],
                  [4, 5, 6]],

                 [[7, 8, 9],
                  [10, 11, 12]] ])

**Slice entire first block**

In [32]:
print(arr[0, :, :])

[[1 2 3]
 [4 5 6]]


**Slice second block’s first row**

In [33]:
print(arr[1, 0, :])

[7 8 9]


**Slice all blocks, all rows, columns 0 to 1**

In [34]:
print(arr[:, :, 0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


**Slice with steps (every 2nd element)**

In [35]:
print(arr[:, :, ::2])

[[[ 1  3]
  [ 4  6]]

 [[ 7  9]
  [10 12]]]


**Array Reshaping**<br>
**1D Array to 2D**

In [36]:
arr5 = np.array([1, 2, 3, 4, 5, 6])

new_arr1 = arr5.reshape(2, 3)

print(new_arr1)

[[1 2 3]
 [4 5 6]]


**1D Array to 3D**

In [37]:
arr6 = np.array([1, 2, 3, 4, 5, 6])

new_arr6 = arr6.reshape(2, 1, 3)
print(new_arr6)


[[[1 2 3]]

 [[4 5 6]]]


**Flatten (make 1D)**

In [38]:
new_arr6.flatten()

array([1, 2, 3, 4, 5, 6])

**Matrix Operations**

**Matrix multiplication**

In [39]:
a = np.array([[9, 2],
              [3, 4]])

b = np.array([[6, 3],
              [7, 8]])

np.dot(a, b)

array([[68, 43],
       [46, 41]])

**Transpose**

In [40]:
a.T

array([[9, 3],
       [2, 4]])

In [41]:
b.T

array([[6, 7],
       [3, 8]])

**Determinant**

In [42]:
np.linalg.det(a)

np.float64(30.000000000000014)

In [43]:
np.linalg.det(b)

np.float64(27.0)

**Inverse**

In [44]:
np.linalg.inv(a)

array([[ 0.13333333, -0.06666667],
       [-0.1       ,  0.3       ]])

In [45]:
np.linalg.inv(b)

array([[ 0.2962963 , -0.11111111],
       [-0.25925926,  0.22222222]])

**Random Numbers with NumPy**

**Random integer**

In [46]:
np.random.randint(1, 10)

4

**Random array**

In [47]:
np.random.rand(3, 3)

array([[0.26859151, 0.75417997, 0.41020723],
       [0.65786506, 0.54463038, 0.97297384],
       [0.85792822, 0.98050733, 0.38769766]])

**Normal distribution**

In [48]:
np.random.randn(5)

array([-0.09371726,  0.08943958,  0.44674384,  0.4168718 ,  0.54556842])

**Shuffle array**

In [49]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[3 5 4 2 1]


**Broadcasting**

In [50]:
arr = np.array([1, 2, 3])
print(arr + 10)

[11 12 13]


**Stacking**

**Horizontal stack**

In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

**Vertical stack**

In [52]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

**Boolean Indexing**

In [53]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 30])

[40 50]


**Copy vs View**

**Copy → Independent**

In [54]:
a = np.array([78, 67, 32])
b = a.copy()
b[0] = 100
print(a)

[78 67 32]


**View → Linked to original array**

In [55]:
c = a.view()
c[0] = 200
print(a)

[200  67  32]


**Joining NumPy Arrays**

In [56]:
#Joining two 1-D arrays
arr1 = np.array(["Toyota", "Hyundai", "Kia", "Honda"])
arr2 = np.array(["Mercedes-Benz", "BMW", "Audi", "Rolls-Royce"])

result = np.concatenate((arr1, arr2))
print(result)

['Toyota' 'Hyundai' 'Kia' 'Honda' 'Mercedes-Benz' 'BMW' 'Audi'
 'Rolls-Royce']


In [57]:
#Joining two 2-D arrays (row-wise)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
#Joining two 2-D arrays (column-wise)
result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


**Splitting NumPy Arrays**

In [59]:
#Splitting a 1-D array into 3 parts
arr = np.array([1, 2, 3, 4, 5, 6])

result = np.array_split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


**Horizontal Split**

In [60]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.hsplit(arr, 3)
print(result)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


**Vertical Split**

In [61]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.vsplit(arr, 2)
print(result)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


**Sorting Arrays**

**Sorting a 1D Array**

In [62]:
arr = np.array([5, 2, 8, 1, 9])
sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 5 8 9]


**Sorting a 2D Array**

In [63]:
arr = np.array([[3, 1, 2],
                [9, 5, 7]])

sorted_arr = np.sort(arr)
print(sorted_arr)

[[1 2 3]
 [5 7 9]]


In [64]:
#Sorting column-wise (axis=0)
sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)

[[3 1 2]
 [9 5 7]]


**Sorting a 3D Array**

In [65]:
arr = np.array([[[3, 1, 2], [9, 7, 8]],
                [[6, 4, 5], [1, 3, 2]]])

sorted_arr = np.sort(arr)
print(sorted_arr)

[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [1 2 3]]]


**Sorting Strings**

In [66]:
arr = np.array(["banana", "apple", "cherry"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


**Sorting in Descending Order**

In [67]:
arr = np.array([5, 2, 9, 1])
result = np.sort(arr)[::-1]

print(result)

[9 5 2 1]


**Sorting Structured Arrays**

In [68]:
data = np.array(
    [('Ram', 25), ('Laxman', 20), ('Sita', 30)],
    dtype=[('name', 'U10'), ('age', int)]
)

sorted_data = np.sort(data, order='age')
print(sorted_data)

[('Laxman', 20) ('Ram', 25) ('Sita', 30)]
